In [ ]:
import pandas as pd
import numpy as np

file_path = "../data/raw/E Commerce Dataset.xlsx"

df = pd.read_excel(file_path, sheet_name="E Comm")

print(df.shape)

(5630, 20)

In [ ]:
df_clean = df.copy()

In [ ]:
print("duplicated rows:",df_clean.duplicated().sum())

duplicated rows: 0

In [ ]:
df_clean = df_clean.drop_duplicates()

In [ ]:
df_clean.head()

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

In [ ]:
print("after removing the duplicated rows:",df_clean.shape)

after removing the duplicated rows: (5630, 20)

In [ ]:
print("dulicate customer IDs:",df_clean["CustomerID"].duplicated().sum())

dulicate customer IDs: 0

In [ ]:
duplicate_customers = df_clean[
    df_clean["CustomerID"].duplicated(keep=False)
]

duplicate_customers

Empty DataFrame
Columns: [CustomerID, Churn, Tenure, PreferredLoginDevice, CityTier, WarehouseToHome, PreferredPaymentMode, Gender, HourSpendOnApp, NumberOfDeviceRegistered, PreferedOrderCat, SatisfactionScore, MaritalStatus, NumberOfAddress, Complain, OrderAmountHikeFromlastYear, CouponUsed, OrderCount, DaySinceLastOrder, CashbackAmount]
Index: []

In [ ]:
missing = pd.DataFrame({
    "Missing Count": df_clean.isnull().sum(),
    "Missing %": df_clean.isnull().mean() * 100
})

missing = missing.sort_values(
    "Missing Count",
    ascending=False
)

missing

                             Missing Count  Missing %
DaySinceLastOrder                      307   5.452931
OrderAmountHikeFromlastYear            265   4.706927
Tenure                                 264   4.689165
OrderCount                             258   4.582593
CouponUsed                             256   4.547069
HourSpendOnApp                         255   4.529307
WarehouseToHome                        251   4.458259
CustomerID                               0   0.000000
PreferredLoginDevice                     0   0.000000
Churn                                    0   0.000000
PreferredPaymentMode                     0   0.000000
CityTier                                 0   0.000000
SatisfactionScore                        0   0.000000
PreferedOrderCat                         0   0.000000
NumberOfDeviceRegistered                 0   0.000000
Gender                                   0   0.000000
Complain                                 0   0.000000
NumberOfAddress                          0   0.000000
MaritalStatus                            0   0.000000
CashbackAmount                           0   0.000000

In [ ]:
numerical_cols = df_clean.select_dtypes(
    include=np.number
).columns

In [ ]:
for col in numerical_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

In [ ]:
num_cols_to_impute = [
    col for col in numerical_cols
    if col not in ["CustomerID", "Churn"]
]

for col in num_cols_to_impute:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

In [ ]:
categorical_cols = df_clean.select_dtypes(
    include="object"
).columns.tolist()

print(categorical_cols)

['PreferredLoginDevice', 'PreferredPaymentMode', 'Gender', 'PreferedOrderCat', 'MaritalStatus']

C:\Users\hemag\AppData\Local\Temp\ipykernel_35148\618250573.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df_clean.select_dtypes(

In [ ]:
df_clean[categorical_cols].isnull().sum()

PreferredLoginDevice    0
PreferredPaymentMode    0
Gender                  0
PreferedOrderCat        0
MaritalStatus           0
dtype: int64

In [ ]:
for col in categorical_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

In [ ]:
df_clean.dtypes

CustomerID                       int64
Churn                            int64
Tenure                         float64
PreferredLoginDevice               str
CityTier                         int64
WarehouseToHome                float64
PreferredPaymentMode               str
Gender                             str
HourSpendOnApp                 float64
NumberOfDeviceRegistered         int64
PreferedOrderCat                   str
SatisfactionScore                int64
MaritalStatus                      str
NumberOfAddress                  int64
Complain                         int64
OrderAmountHikeFromlastYear    float64
CouponUsed                     float64
OrderCount                     float64
DaySinceLastOrder              float64
CashbackAmount                 float64
dtype: object

In [ ]:
df_clean["Tenure"] = pd.to_numeric(
    df_clean["Tenure"],
    errors="coerce"
)

In [ ]:
df_clean.dtypes

CustomerID                       int64
Churn                            int64
Tenure                         float64
PreferredLoginDevice               str
CityTier                         int64
WarehouseToHome                float64
PreferredPaymentMode               str
Gender                             str
HourSpendOnApp                 float64
NumberOfDeviceRegistered         int64
PreferedOrderCat                   str
SatisfactionScore                int64
MaritalStatus                      str
NumberOfAddress                  int64
Complain                         int64
OrderAmountHikeFromlastYear    float64
CouponUsed                     float64
OrderCount                     float64
DaySinceLastOrder              float64
CashbackAmount                 float64
dtype: object

In [ ]:
df_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
CustomerID,5630.0,52815.500000,1625.385339,50001.0,51408.25,52815.50,54222.7500,55630.00
Churn,5630.0,0.168384,0.374240,0.0,0.00,0.00,0.0000,1.00
Tenure,5630.0,10.134103,8.357951,0.0,3.00,9.00,15.0000,61.00
CityTier,5630.0,1.654707,0.915389,1.0,1.00,1.00,3.0000,3.00
WarehouseToHome,5630.0,15.566785,8.345961,5.0,9.00,14.00,20.0000,127.00
HourSpendOnApp,5630.0,2.934636,0.705528,0.0,2.00,3.00,3.0000,5.00
NumberOfDeviceRegistered,5630.0,3.688988,1.023999,1.0,3.00,4.00,4.0000,6.00
SatisfactionScore,5630.0,3.066785,1.380194,1.0,2.00,3.00,4.0000,5.00
NumberOfAddress,5630.0,4.214032,2.583586,1.0,2.00,3.00,6.0000,22.00
Complain,5630.0,0.284902,0.451408,0.0,0.00,0.00,1.0000,1.00
OrderAmountHikeFromlastYear,5630.0,15.674600,3.591058,11.0,13.00,15.00,18.0000,26.00
CouponUsed,5630.0,1.716874,1.857640,0.0,1.00,1.00,2.0000,16.00
OrderCount,5630.0,2.961812,2.879248,1.0,1.00,2.00,3.0000,16.00
DaySinceLastOrder,5630.0,4.459325,3.570626,0.0,2.00,3.00,7.0000,46.00
CashbackAmount,5630.0,177.223030,49.207036,0.0,145.77,163.28,196.3925,324.99

In [ ]:
df_clean["Churn"].value_counts()

Churn
0    4682
1     948
Name: count, dtype: int64

In [ ]:
df_clean["SatisfactionScore"].value_counts().sort_index()

SatisfactionScore
1    1164
2     586
3    1698
4    1074
5    1108
Name: count, dtype: int64

In [ ]:
df_clean["Tenure"].describe()

count    5630.000000
mean       10.134103
std         8.357951
min         0.000000
25%         3.000000
50%         9.000000
75%        15.000000
max        61.000000
Name: Tenure, dtype: float64

In [ ]:
df_clean["OrderCount"].describe()

count    5630.000000
mean        2.961812
std         2.879248
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max        16.000000
Name: OrderCount, dtype: float64

In [ ]:
df_clean["DaySinceLastOrder"].describe()

count    5630.000000
mean        4.459325
std         3.570626
min         0.000000
25%         2.000000
50%         3.000000
75%         7.000000
max        46.000000
Name: DaySinceLastOrder, dtype: float64

In [ ]:
df_clean[df_clean["Tenure"] < 0]

Empty DataFrame
Columns: [CustomerID, Churn, Tenure, PreferredLoginDevice, CityTier, WarehouseToHome, PreferredPaymentMode, Gender, HourSpendOnApp, NumberOfDeviceRegistered, PreferedOrderCat, SatisfactionScore, MaritalStatus, NumberOfAddress, Complain, OrderAmountHikeFromlastYear, CouponUsed, OrderCount, DaySinceLastOrder, CashbackAmount]
Index: []

In [ ]:
df_clean[df_clean["OrderCount"] < 0]

Empty DataFrame
Columns: [CustomerID, Churn, Tenure, PreferredLoginDevice, CityTier, WarehouseToHome, PreferredPaymentMode, Gender, HourSpendOnApp, NumberOfDeviceRegistered, PreferedOrderCat, SatisfactionScore, MaritalStatus, NumberOfAddress, Complain, OrderAmountHikeFromlastYear, CouponUsed, OrderCount, DaySinceLastOrder, CashbackAmount]
Index: []

In [ ]:
for col in categorical_cols:
    print(f"\n{col}")
    print(df_clean[col].value_counts(dropna=False))

PreferredLoginDevice
PreferredLoginDevice
Mobile Phone    2765
Computer        1634
Phone           1231
Name: count, dtype: int64

PreferredPaymentMode
PreferredPaymentMode
Debit Card          2314
Credit Card         1501
E wallet             614
UPI                  414
COD                  365
CC                   273
Cash on Delivery     149
Name: count, dtype: int64

Gender
Gender
Male      3384
Female    2246
Name: count, dtype: int64

PreferedOrderCat
PreferedOrderCat
Laptop & Accessory    2050
Mobile Phone          1271
Fashion                826
Mobile                 809
Grocery                410
Others                 264
Name: count, dtype: int64

MaritalStatus
MaritalStatus
Married     2986
Single      1796
Divorced     848
Name: count, dtype: int64

In [ ]:
df_clean["Gender"] = (
    df_clean["Gender"]
    .astype(str)
    .str.strip()
    .str.title()
)

In [ ]:
def find_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return df[
        (df[column] < lower) |
        (df[column] > upper)
    ]

In [ ]:
for col in [
    "Tenure",
    "WarehouseToHome",
    "HourSpendOnApp",
    "OrderAmountHikeFromlastYear",
    "CouponUsed",
    "OrderCount",
    "DaySinceLastOrder",
    "CashbackAmount"
]:
    print(col, len(find_outliers(df_clean, col)))

Tenure 4
WarehouseToHome 2
HourSpendOnApp 6
OrderAmountHikeFromlastYear 33
CouponUsed 629
OrderCount 703
DaySinceLastOrder 62
CashbackAmount 438

In [ ]:
df_clean.isnull().sum()

CustomerID                     0
Churn                          0
Tenure                         0
PreferredLoginDevice           0
CityTier                       0
WarehouseToHome                0
PreferredPaymentMode           0
Gender                         0
HourSpendOnApp                 0
NumberOfDeviceRegistered       0
PreferedOrderCat               0
SatisfactionScore              0
MaritalStatus                  0
NumberOfAddress                0
Complain                       0
OrderAmountHikeFromlastYear    0
CouponUsed                     0
OrderCount                     0
DaySinceLastOrder              0
CashbackAmount                 0
dtype: int64

In [ ]:
print("Duplicate rows:", df_clean.duplicated().sum())

Duplicate rows: 0

In [ ]:
print("Original shape:", df.shape)
print("Cleaned shape :", df_clean.shape)

Original shape: (5630, 20)
Cleaned shape : (5630, 20)

In [ ]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [ ]:
df_clean.to_csv(
    "../data/processed/ecommerce_churn_cleaned.csv",
    index=False
)

In [ ]:
print("Shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nDuplicate Customer IDs:")
print(df["CustomerID"].duplicated().sum())

print("\nData types:")
print(df.dtypes)

print("\nChurn distribution:")
print(df["Churn"].value_counts())

print("\nNumerical summary:")
print(df.describe().T)

Shape: (5630, 20)

Missing values:
CustomerID                       0
Churn                            0
Tenure                         264
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                251
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 255
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    265
CouponUsed                     256
OrderCount                     258
DaySinceLastOrder              307
CashbackAmount                   0
dtype: int64

Duplicate rows:
0

Duplicate Customer IDs:
0

Data types:
CustomerID                       int64
Churn                            int64
Tenure                         float64
PreferredLoginDevice               str
CityTier                         int64
WarehouseToHome                float64
PreferredPaymentMode               str
Gender                             str
HourSpendOnApp                 float64
NumberOfDeviceRegistered         int64
PreferedOrderCat                   str
SatisfactionScore                int64
MaritalStatus                      str
NumberOfAddress                  int64
Complain                         int64
OrderAmountHikeFromlastYear    float64
CouponUsed                     float64
OrderCount                     float64
DaySinceLastOrder              float64
CashbackAmount                 float64
dtype: object

Churn distribution:
Churn
0    4682
1     948
Name: count, dtype: int64

Numerical summary:
                              count          mean          std      min  \
CustomerID                   5630.0  52815.500000  1625.385339  50001.0
Churn                        5630.0      0.168384     0.374240      0.0
Tenure                       5366.0     10.189899     8.557241      0.0
CityTier                     5630.0      1.654707     0.915389      1.0
WarehouseToHome              5379.0     15.639896     8.531475      5.0
HourSpendOnApp               5375.0      2.931535     0.721926      0.0
NumberOfDeviceRegistered     5630.0      3.688988     1.023999      1.0
SatisfactionScore            5630.0      3.066785     1.380194      1.0
NumberOfAddress              5630.0      4.214032     2.583586      1.0
Complain                     5630.0      0.284902     0.451408      0.0
OrderAmountHikeFromlastYear  5365.0     15.707922     3.675485     11.0
CouponUsed                   5374.0      1.751023     1.894621      0.0
OrderCount                   5372.0      3.008004     2.939680      1.0
DaySinceLastOrder            5323.0      4.543491     3.654433      0.0
CashbackAmount               5630.0    177.223030    49.207036      0.0

                                  25%       50%         75%       max
CustomerID                   51408.25  52815.50  54222.7500  55630.00
Churn                            0.00      0.00      0.0000      1.00
Tenure                           2.00      9.00     16.0000     61.00
CityTier                         1.00      1.00      3.0000      3.00
WarehouseToHome                  9.00     14.00     20.0000    127.00
HourSpendOnApp                   2.00      3.00      3.0000      5.00
NumberOfDeviceRegistered         3.00      4.00      4.0000      6.00
SatisfactionScore                2.00      3.00      4.0000      5.00
NumberOfAddress                  2.00      3.00      6.0000     22.00
Complain                         0.00      0.00      1.0000      1.00
OrderAmountHikeFromlastYear     13.00     15.00     18.0000     26.00
CouponUsed                       1.00      1.00      2.0000     16.00
OrderCount                       1.00      2.00      3.0000     16.00
DaySinceLastOrder                2.00      3.00      7.0000     46.00
CashbackAmount                 145.77    163.28    196.3925    324.99